### ISSUE TITLE
add env vars for nginx in docker compose

### ISSUE THREAD

**Issue by chamanbravo** [chamanbravo/upstat#10]
use env rather than hardcode ports
```
nginx:
    restart: unless-stopped
    image: nginx:1.21.1-alpine
    ports:
      - "80:80"
```
use this instead
`$IPADDR:$PORT:80`
