### ISSUE TITLE
Login default?

### ISSUE THREAD

**Issue by zarevskaya** [chamanbravo/upstat#46]
Hi, 

Thanks for this app!

How to set an account?

Thank you

**Comment by zarevskaya** [comment]
Thanks for the answer.

when I launch the app for the first time it says welcome back directly.
![Screenshot_20240807_143547](https://github.com/user-attachments/assets/30536cab-5581-4394-b429-81243fee611c)

I'm in private mode on Firefox.

It launches directly on this URL:

http://192.168.1.152:3000/auth/

**Comment by zarevskaya** [comment]
I did this:

sudo git clone https://github.com/chamanbravo/upstat.git
sudo cp .sample.env  .env
docker compose up -d

**Comment by chamanbravo** [comment]
```
version: '3.4'
services:
  db:
    restart: unless-stopped
    image: postgres:13-alpine
    environment:
      - POSTGRES_DB=upstat
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5

  api:
    restart: unless-stopped
    build:
      context: ./
    environment:
      - POSTGRES_DSN=postgres://postgres:postgres@db:5432/upstat?sslmode=disable
      - JWT_SECRET_KEY=asdfjaskljd
    depends_on:
      db:
        condition: service_healthy

  web:
    restart: unless-stopped
    build:
      context: web
    ports:
      - "3000:3000"
    depends_on:
      db:
        condition: service_healthy

volumes:
  postgres_data:
```
try this docker compose file
